name: Deploy - funds-api

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      STACK_NAME: funds-api-repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Eliminar stack si está en ROLLBACK_COMPLETE
        run: |
          STATUS=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].StackStatus" \
            --output text || echo "NOT_FOUND")
          if [ "$STATUS" = "ROLLBACK_COMPLETE" ]; then
            aws cloudformation delete-stack --stack-name $STACK_NAME
            aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME
          fi

      - name: Crear repositorio ECR público (CloudFormation)
        run: |
          aws cloudformation deploy \
            --template-file ecr-repo.yaml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Obtener URI del repositorio público
        id: get-repo-uri
        run: |
          URI=$(aws cloudformation describe-stacks \
            --stack-name funds-client-repo \
            --query "Stacks[0].Outputs[?OutputKey=='FrontendRepositoryUri'].OutputValue" \
            --output text)
          echo "REPO_URI=$URI" >> $GITHUB_ENV
          echo "Repository URI: $URI"

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: docker build -t funds-client .

      - name: Tag Docker image
        run: docker tag funds-client:latest ${{ env.REPO_URI }}:latest

      - name: Push Docker image
        run: docker push ${{ env.REPO_URI }}:latest

      - name: Desplegar infraestructura (CloudFormation)
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-frontend.yaml \
            --stack-name funds-api-infra \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides ImageUri=${{ env.REPO_URI }}:latest
